### ISSUE TITLE
Some selectors are selecting the min informative items

### ISSUE THREAD

**Issue by machow** [douglasrizzo/catsim#11]
I may have missed something, but it looks like some selectors are selecting minimally informative items.

https://github.com/douglasrizzo/catsim/blob/master/catsim/selection.py#L840-L842

Since `np.argsort()` sorts in ascending order, the Randomesque selector is choosing from the least X informative items.

Should be a quick fix! Either by multiplying info by -1 or using `reversed`. Happy to open a PR!

**Comment by douglasrizzo** [comment]
Hey, thanks for the contribution! If you want to open two PRs or one PR for both issues to take credit for the fix, go ahead. I can also take a and fix it later.
