### ISSUE TITLE
Real Time data

### ISSUE THREAD

**Issue by EverAPC** [douglasrizzo/catsim#18]
Hi,
Can the code be applied to real time data in the place of simulated ones.

**Comment by douglasrizzo** [comment]
It can. I have some examples where you can use initializers, selectors, estimators and stoppers inside your own code or script, without a simulator.

http://douglasrizzo.com.br/catsim/introduction.html#autonomous-usage

**Comment by douglasrizzo** [comment]
Just to be clear, your program will be responsible for providing item parameters and students responses, and catsim will provide proficiency estimations, which items to apply next and or not a test must be stopped.

**Comment by EverAPC** [comment]
Hi,
Thank you for the immediate clarification.
I have few more concerns:
1) Can't this be used for polytomous outcomes?2) Can this be used to give a score for a particular item?3) Should this be used only for CAT purposes?
Thank you 
Warm Regards,Princy    On Wednesday, November 27, 2019, 02:55:19 AM GMT+5:30, Douglas De Rizzo Meneghetti <notifications@github.com> wrote:  
 
 
Just to be clear, your program will be responsible for providing item parameters and students responses, and catsim will provide proficiency estimations, which items to apply next and or not a test must be stopped.

**Comment by douglasrizzo** [comment]
1. No, only dichotomous answers;
2. If, by score, you mean estimating item parameters, then no;
3. I don't know what do you mean by that. I am going with the hunch you're looking for an IRT package on Python and not explicitly a package focused on adaptive testing. `catsim` has [a module](http://douglasrizzo.com.br/catsim/irt.html) with functions for the 1 2 3 and 4PL models, but I don't believe it is a full replacement for specialized packages available in other languages, such as the mirt package in the R language.
