### ISSUE TITLE
No tutorial in the documentation

### ISSUE THREAD

**Issue by KayvanShah1** [douglasrizzo/catsim#20]
It is that we can understand the base methods and its uses but seems unaware about its usage.

A python notebook where you can view how one one use it on small exaple of student id and question response dataset would become greatly useful and help tracking further errors if encountered.

**Comment by douglasrizzo** [comment]
Hi there. There are examples available in the documentation [here](https://douglasrizzo.com.br/catsim/introduction.html#examples). In any case, I'll see if I can provide a Jupyter Notebook in the next few days.

**Comment by douglasrizzo** [comment]
See if this helps: https://douglasrizzo.com.br/catsim/examples.html

There is a link to a Colab Notebook too.

**Comment by KayvanShah1** [comment]
I actually have data that works fine with implementation of Rasch model.

![Screenshot (5)](https://user-images.githubusercontent.com/59110083/87422925-206f9900-c5f7-11ea-9ce3-2b964b241a86.png)

I want to implement IRT 4 parameter model for better results but unable to do so.
Getting messed up by the theory and not able to understand how to use catsim with it

**Comment by douglasrizzo** [comment]
This package does not estimate item parameters. You should do it with an external program.

**Comment by KayvanShah1** [comment]
Thank you for your guidance.

**Comment by douglasrizzo** [comment]
catsim is specialized in computerized adaptive tests, it doesn't delve into item parameter estimation. My suggestion, if you want to apply other logistic models to your data, is to try using the [mirt package](https://cran.r-project.org/web/packages/mirt/mirt.pdf) in the R language, which is free and quite simple to use. Then, if you're still interested in using those parameters in a CAT, you can come back to catsim and use them here.

Item parameter estimation is something I have been interested in adding to catsim for quite a while, but I also don't have the expertise for that right now.

**Comment by onlyfew** [comment]
> See if this helps: https://douglasrizzo.com.br/catsim/examples.html看看这是否有帮助：https://douglasrizzo.com.br/catsim/examples.html
> 
> There is a link to a Colab Notebook too.还有 Colab Notebook 的链接。

404 now

**Comment by douglasrizzo** [comment]
Try the Colab notebook in the README, I've updated the link.
