### ISSUE TITLE
Link to (integrate with?) Python IRT estimation libraries

### ISSUE THREAD

**Issue by frankier** [douglasrizzo/catsim#21]
Hi! This looks like a great library. Thanks for your work on it!

One thing that might be nice is to link to some projects which can estimate IRT parameters. since this seems to be a common request. I've found the following which seem to be maintained:

https://github.com/nd-ball/py-irt
https://github.com/eribean/girth_mcmc
https://github.com/eribean/girth

**Comment by douglasrizzo** [comment]
Thanks for the links, I actually wasn't aware parameter estimation was implemented in Python. In the past I found [pyirt](https://github.com/17zuoye/pyirt) and a library from Khan Academy, called "avocado" or "guacamole", but it's gone from their GitHub.

I'll try these out and then add them to the README and documentation.

**Comment by eribean** [comment]
@douglasrizzo Thanks for the shout out in the README! I'm constantly working on GIRTH to improve it!
