### ISSUE TITLE
Initializer

### ISSUE THREAD

**Issue by amymaries** [douglasrizzo/catsim#28]
When trying to run your Catsim in Colab, step #4, initializing theta for the examinee, gives me the following error code: 

NameError: name 'initializer' is not defined.

I'm trying to read your code here, but I'm new to Python. Could you help?

**Comment by douglasrizzo** [comment]
Hi, the link in the README was for an incomplete Colab notebook. You can find a more complete Colab in this link: https://colab.research.google.com/drive/1dBcpXxHuc9YXv9yGllxlahx585hEmdbn.

I have also fixed the link in the project's home page. Thanks for pointing that out to me.

**Comment by amymaries** [comment]
Thank you so much for that project! It was really helpful! I want to build a CAT math placement test for a particular math curriculum and I wasn't sure where to start. This gave me lots of ideas. I would just offer it to my math students, free, on my personal website. Would you mind if I used the code in this repository?

**Comment by douglasrizzo** [comment]
Go ahead! Everything is free and open source. I believe people have been using catsim on commercial applications too. The license allows it.
