### ISSUE TITLE
The logic of b parameter

### ISSUE THREAD

**Issue by Milad221157** [douglasrizzo/catsim#33]
Hey Douglas 👋,

I have a question about the package. Shouldn't the logic of the package dictate that if the examinee answers one question correctly, the next question must have a higher "b" parameter, and vice versa? I'm wondering if it's possible that the question selection method isn't always following this logic.

I experimented with the package, and at times, I chose the correct answer, but some questions seemed to have lower "b" parameters than expected. I'd appreciate your input on this.

Thanks for your help! 🙏

**Comment by douglasrizzo** [comment]
Hi Milad.

No. At each step of the test, the best item to be selected is the one that has maximum information (i.e. the one that has the maximum output of [this function](https://douglasrizzo.com.br/catsim/irt.html#catsim.irt.inf)) for the examinee's current theta. For the 1PL and 2PL models, this item is the one whose b parameter is closest to the current theta parameter of the examinee. That is not true for the 3PL and 4PL models.

Basically, the fact that a harder item can be guessed correctly with high probability can make it less informative than an easier item that has a lower probability of being guessed correctly. So, under the 3PL and 4PL models, there are situations in which an item with lower b may be more informative than another item whose b is closer to the examinee's current theta.

Also, most item selection methods available in catsim have constraints that may not allow the item of maximum information to be selected at every step of test.

If you think you've found a bug, let's try to reproduce and I'll see what I can do to fix it!

**Comment by douglasrizzo** [comment]
We can reopen this if more questions come up.
